### ISSUE TITLE
Why the forking?

### ISSUE THREAD

**Issue by Not-Nik** [RUSshy/contact_me#1]
I don't get it, you fork projects, don't change anything and just leave them to rot forever on your account. If you wanted to show appreciation for a project, you can just star it, so why the extra forking?

**Comment by RUSshy** [comment]
Why do you fucking lie?

Every fork i made has a ``path-1`` branch, that's because i sent a PR from the website directly

Go ask microsoft shitty developpers why they force copies to make simple changes

And he said "i make extra forking" you dumb microsoft employee

**Comment by Not-Nik** [comment]
Damn, it was just a question, no need to be that aggressive.

**Comment by RUSshy** [comment]
Because you lie

And i beat you

[![stats](https://github-readme-stats.vercel.app/api?username=RUSshy&show_icons=true&theme=dark&count_private=true)](https://github.com/anuraghazra/github-readme-stats)

**Comment by RUSshy** [comment]
even that shit doesn't work 
![image](https://user-images.githubusercontent.com/18348637/106977968-9a19d080-675b-11eb-911b-9b66d88143b1.png)

be offended at that instead of being offended at me, people spit non working bloat everywhere

**Comment by Not-Nik** [comment]
I ain't being offended at nobody. You should really learn the difference between lying and not seeing something. Btw, you do have quite some forks without a `patch-1` or any changes for that matter:
- RUSshy/emscripten
- RUSshy/de4dot (you aint telling me thats a real impovement)
- RUSshy/raylib-games
- RUSshy/zls
- RUSshy/BlobEditor
- RUSshy/d2sqlite3
- RUSshy/zig-upaya
- RUSshy/dark
- RUSshy/dash-contrib-docset-feeds
- RUSshy/runtime

And that is just the first page of all of your repositories. So asking me why I'm lying, you should ask yourself that question.

**Comment by RUSshy** [comment]
If they don't have patch-1, they either have other name, or have local branch not ready for PR

Why you spy me?

**Comment by Not-Nik** [comment]
Because you're being a douchebag

**Comment by RUSshy** [comment]
oh, thanks :D
let's unbloat the world together
