### ISSUE TITLE
Urgent matter: rsvp

### ISSUE THREAD

**Issue by endigma** [RUSshy/contact_me#2]
UBA NIGERIA LAGOS,
E-mail:  ubaafriica@gmail.com

Attention Beneficiary
Latest development, we bring to your notice:Due to bad network we are having here in Africa we could not be able to complete your transfer through Bank to bank transfer Or online Transfer as programmed.Our network here will not carry on the programming, so we decided to use ATM MASTER CARD method to finalize the transaction.We have programmed an ATM MASTER CARD with your name and uploaded your total fund of (US$4.5Million) in the Card so that you will be withdrawing with it in any ATM MACHINE. The ATM MASTER CARD works worldwide and the daily amount WITHDRAW according to our programming system is(US$9,000.00) Fifteen Thousand Dollars only.
I Mr.Tony Elumelu, have made the delivery arrangement with DHL DELIVERY COMPANY NIGERIA that will carry on the delivery to your home address and their director told me that Delivery of the ATM MASTER CARD to your house will be smooth with out delay.He assured me that their Company takes good 4-days to complete any delivery registered with accurate address. So you are advised to send your full address such as:
Full Name:____________________
Home Address:________________
Country:______________________
State:________________________
City:_________________________
Zip code:_____________________
Telephone Number:_____________
Please your urgent reply will be appreciated for immediate registering of your ATM CARD.YOUR FUND HAS BEEN CREDITED INTO ATM CARD, reply back only on this email ubaafriica@gmail.com

YOUR FUND HAS BEEN CREDITED INTO ATM CARD, reply back only on this email  ubaafriica@gmail.com

Mr.Tony Elumelu
United Bank of Africa (UBA-NIGERIA)

**Comment by RUSshy** [comment]
Money sent ![BOGGED](https://cdn.frankerfacez.com/emoticon/274629/1)
